---
title: "Josh_DataWrangling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
```

## HPI vs CPi and SP&500 vs Case Shiller HPI

```{r}
#Import CPI data
CPI <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/USACPIALLMINMEI.xls", range = "A11:B265") %>%
    #Renaming columns to make sense
  rename(Date = "observation_date", ConsumerPriceIndex = "USACPIALLMINMEI") %>%
    #formatting the class of this column for visualization
  mutate(Date = as.Date(as.character(Date), format = "%Y-%m-%d"))
  
#Import HPI
HPI <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/CSUSHPINSA.xls", range = "A11:B265") %>%
    #Renaming columns to make sense
  rename(Date = "observation_date", HousingPriceIndex = "CSUSHPINSA") %>%
    #formatting the class of this column for visualization
  mutate(Date = as.Date(as.character(Date), format = "%Y-%m-%d"))

#Join two tables together
CPIHPI <- HPI %>%
  left_join(CPI, by = "Date") %>%
  #pivot to long dataset for visualization
  pivot_longer(!Date, values_to = "Index_Values", names_to = "Index_Type")

#Import S&P 500 data with Case Shiller Home Price
SPHomePrice <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/sp-500-vs-home-prices.xls.xlsx") %>%
  #Rename columns to legible names
  rename(DateTime = "S&P 500 vs. Home Prices", "SP_500" = "...2", "Case_Shiller_Home_Price_Index" = "...3") %>%
  #Filter for 2 years worth of data from 2019-2021
  filter(DateTime > "2019-02-01") %>%
  #filtering out one row in which does not contain observation
  filter(DateTime != "DateTime") %>%
  #formattting columns to make sure they work in computations and visualizations
  mutate(
    Date = as.Date(DateTime, format = "%Y-%m-%d"),
    MY = format(Date, format = "%Y-%m"),
    SP_500 = as.double(SP_500),
    Case_Shiller_Home_Price_Index = as.double(Case_Shiller_Home_Price_Index)
    ) %>%
  #removing unnecessary column
  select(-DateTime) %>%
  #Pivot to long dataset for visualization
  pivot_longer(!Date & !MY, names_to = "Index_Type", values_to = "Index_Value") %>%
  #filtering out NA values
  filter(Index_Value != "NA") %>%
  #Group by month and year to find datapoint for last day of each month
  group_by(MY) %>%
  filter(Date == max(Date)) %>%
  #ungroup to allow computations for percentage change
  ungroup() %>%
  #arrange by index type and date to order data correctly
  arrange(Index_Type, Date) %>%
  #Calculate percentage change
  mutate(
    pct_chg = as.double(100 * (Index_Value - lag(Index_Value))/lag(Index_Value))
         ) %>%
  #Change initial percentage change to 0 for visualization
  within(pct_chg[Date == '2019-02-28'] <- as.numeric('0'))

```

## Building Permit vs Construction Material Index Percentage Change

```{r}
#Import exel sheet with observations only
BP202002 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202002.xls", range = "A8:G74") %>%
  #rename column for legibility
  rename(Region = "...1") %>%
  #filter out NA observations and non-state observations
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  #pivot to long data for visualization
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  #change class of column for visualization
  mutate(Date = as.Date("02-01-2020", "%m-%d-%Y"))

#Continuted for one whole year
BP202003 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202003.xls", range = "A8:G74") %>%
  rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("03-01-2020", "%m-%d-%Y"))

BP202004 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202004.xls", range = "A8:G74") %>%
  rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("04-01-2020", "%m-%d-%Y"))

BP202005 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202005.xls", range = "A8:G74") %>%
  rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("05-01-2020", "%m-%d-%Y"))

BP202006 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202006.xls", range = "A8:G74") %>%
  rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("06-01-2020", "%m-%d-%Y"))

BP202007 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202007.xls", range = "A8:G74") %>%
  rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("07-01-2020", "%m-%d-%Y"))

BP202008 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202008.xls", range = "A8:G74") %>%
 rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("08-01-2020", "%m-%d-%Y"))

BP202009 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202009.xls", range = "A8:G74") %>%
 rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("09-01-2020", "%m-%d-%Y"))

BP202010 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202010.xls", range = "A8:G74") %>%
  rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("10-01-2020", "%m-%d-%Y"))

BP202011 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202011.xls", range = "A8:G74") %>%
  rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("11-01-2020", "%m-%d-%Y"))

BP202012 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202012.xls", range = "A8:G74") %>%
  rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("12-01-2020", "%m-%d-%Y"))

BP202101 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202101.xls", range = "A8:G74") %>%
  rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("01-01-2021", "%m-%d-%Y"))

BP202102 <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/statemonthly_202102.xls", range = "A8:G74") %>%
  rename(Region = "...1") %>%
  filter(Total != "NA") %>%
  filter(!Region == "Northeast Region") %>%
  filter(!Region == "New England Division") %>%   
  filter(!Region == "Middle Atlantic Division") %>%   
  filter(!Region == "Midwest Region") %>%   
  filter(!Region == "East North Central Division") %>%   
  filter(!Region == "West North Central Division") %>%   
  filter(!Region == "South Region") %>%   
  filter(!Region == "South Atlantic Division") %>%   
  filter(!Region == "East South Central Division") %>%   
  filter(!Region == "West South Central Division") %>%   
  filter(!Region == "West Region") %>%   
  filter(!Region == "Mountain Division") %>%   
  filter(!Region == "Pacific Division") %>%
  pivot_longer(cols = !Region, names_to = "Housing_Type", values_to = "Count") %>%
  mutate(Date = as.Date("02-01-2021", "%m-%d-%Y"))

#Building Permits binding together into one dataset
BuildingPermits <- bind_rows(BP202002, BP202003, BP202004, BP202005, BP202006, BP202007, BP202008, BP202009, BP202010, BP202011, BP202012, BP202101, BP202102) %>%
  #Filter for total US numbers
  filter(Housing_Type == "Total") %>%
  #Column no longer needed
  select(-Housing_Type) %>%
  #filter for US total numbers
  filter(Region == "United States") %>%
  #Calculate percentage change and add Data column to merge with ConstructionMaterial
  mutate(
    pct_chg = as.numeric(100 * (Count - lag(Count))/lag(Count)),
    Data = "Building Permits"
         ) %>%
  #set initial percentage change to 0
  within(pct_chg[Date == '2020-02-01'] <- as.numeric('0')) %>%
  #remove unneccessary columns
  select(-Count, -Region)
  

#Import Construction Material Index Data
ConstructionMaterial <- read_excel("/home/class21/jokim21/Git/Blog-Funemployed-Statisticians/Datasets/Joshua/PCU44414441.xls", range = "A11:B37") %>%
  #Rename columns for legibility
  rename(
    Date = "observation_date",
    Material = "PCU44414441"
    ) %>%
  #calculate percentage change and add column to join with BuildingPermits
  mutate(
    pct_chg = as.numeric(100 * (Material - lag(Material))/lag(Material)),
    Data = "Construction Material"
  ) %>%
  #set initial percentage change to 0
  within(pct_chg[Material == "234.6"] <- as.numeric('0')) %>%
  #Remove unncessary columns
  select(-Material)

#Bind these two together for visualization
BPvCM <- ConstructionMaterial %>%
  bind_rows(BuildingPermits)

#Create csv files for easy importation into visualizations
write_csv(BPvCM, file="Datasets/BPvCM.csv")
write_csv(CPIHPI, file="Datasets/CPIHPI.csv")
write_csv(SPHomePrice, file="Datasets/SPHomePrice.csv")
```

# Visualizations
```{r}
SPplot <- SPHomePrice %>%
  ggplot(aes(x=Date, y=pct_chg, group = Index_Type, color = Index_Type)) +
  geom_line() +
  ylab("Percentage Change of Index") +
  theme(legend.position="bottom", legend.background = element_rect(fill="lightblue", size=0.5, linetype="solid")) +
  labs(color = "Index Type") +
  ggtitle("S&P 500 vs. Case Shiller Housing Price Index")
            
SPplot

Indexplot <- CPIHPI %>%
  ggplot(aes(x = Date, y = Index_Values, group = Index_Type, color = Index_Type)) +
  geom_line() +
  geom_point() +
  ylab("Index Values") +
  theme(legend.position="bottom", legend.background = element_rect(fill="lightblue", size=0.5, linetype="solid")) +
  labs(color = "Index Type") +
  ggtitle("Consumer Price Index vs. Housing Price Index")

Indexplot

BPvCMplot <- BPvCM %>%
  ggplot(aes(x=Date, y=pct_chg, group = Data, fill = Data)) +
  geom_area() +
  ylab("Percentage Change") +
  theme(legend.position="bottom", legend.background = element_rect(fill="lightblue", size=0.5, linetype="solid")) +
  labs(fill = "Data") +
  ggtitle("Difference between Building Permits Approved and Construction Material Price")

BPvCMplot
```
